version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - data:/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=signappdb
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    networks:
      - default
    restart: always
volumes:
  data: { }